name: portifolio
description: "Meu portifólio de desenvolvimento Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.20
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - imagens/fotoperfil.png
    - imagens/fundo.jpg
    - imagens/logowhatsapp.png
